/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatproject;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *Gui Class of the Client chat
 * @author idan adam
 */
public class ClientGui extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    static ClientThread client;
    public static boolean isConnected = false;
    public static String username;

    /**
     * Client GUI constructor, initalize the components.
     */
    public ClientGui() {
        initComponents();
        getContentPane().setBackground(new Color(245, 255, 250));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon.png")));
        jDialog1.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icon.png")));
        ErrorMsg.setBackground(new Color(245, 255, 250));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        OkButton = new javax.swing.JButton();
        ErrorMsg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConnectBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatWin = new javax.swing.JTextArea();
        MsgField = new javax.swing.JTextField();
        SendBtn = new javax.swing.JButton();
        nameBox = new javax.swing.JTextField();
        userScrollPanel = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList<>();
        speakerBox = new javax.swing.JCheckBox();

        jDialog1.setTitle("illeagal name");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setIconImage(null);
        jDialog1.setLocationByPlatform(true);
        jDialog1.setSize(new java.awt.Dimension(300, 150));
        jDialog1.setType(java.awt.Window.Type.POPUP);

        OkButton.setText("Ok");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        ErrorMsg.setToolTipText("");

        jLabel3.setText("Please choose other username");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(60, 74, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ErrorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(OkButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SocketChat");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(215, 253, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(189, 244, 187));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ConnectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_connect.png"))); // NOI18N
        ConnectBtn.setAlignmentY(0.0F);
        ConnectBtn.setAutoscrolls(true);
        ConnectBtn.setContentAreaFilled(false);
        ConnectBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConnectBtn.setFocusPainted(false);
        ConnectBtn.setFocusable(false);
        ConnectBtn.setMaximumSize(new java.awt.Dimension(50, 23));
        ConnectBtn.setMinimumSize(new java.awt.Dimension(50, 23));
        ConnectBtn.setPreferredSize(new java.awt.Dimension(50, 23));
        ConnectBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/button_connectp.png"))); // NOI18N
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("name:");

        NameField.setText("John Doe");

        jLabel2.setText("address:");

        AddressField.setText("localhost");

        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_clear.png"))); // NOI18N
        ClearBtn.setContentAreaFilled(false);
        ClearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClearBtn.setMaximumSize(new java.awt.Dimension(50, 31));
        ClearBtn.setMinimumSize(new java.awt.Dimension(50, 31));
        ClearBtn.setPreferredSize(new java.awt.Dimension(50, 31));
        ClearBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/button_clearp.png"))); // NOI18N
        ClearBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/button_clear.png"))); // NOI18N
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        chatWin.setEditable(false);
        chatWin.setBackground(new java.awt.Color(235, 253, 245));
        chatWin.setColumns(20);
        chatWin.setRows(5);
        chatWin.setAlignmentY(0.0F);
        chatWin.setFocusable(false);
        jScrollPane1.setViewportView(chatWin);

        MsgField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                MsgFieldKeyReleased(evt);
            }
        });

        SendBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_send.png"))); // NOI18N
        SendBtn.setAlignmentY(0.0F);
        SendBtn.setContentAreaFilled(false);
        SendBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SendBtn.setFocusable(false);
        SendBtn.setMargin(new java.awt.Insets(0, 14, 3, 14));
        SendBtn.setPreferredSize(new java.awt.Dimension(55, 31));
        SendBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/button_sendp.png"))); // NOI18N
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });

        nameBox.setText("0");

        usersList.setBackground(new java.awt.Color(235, 253, 245));
        usersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                usersListValueChanged(evt);
            }
        });
        userScrollPanel.setViewportView(usersList);

        speakerBox.setBorderPaintedFlat(true);
        speakerBox.setContentAreaFilled(false);
        speakerBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        speakerBox.setFocusable(false);
        speakerBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speakeron.png"))); // NOI18N
        speakerBox.setMargin(new java.awt.Insets(0, 2, 3, 2));
        speakerBox.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/speakeroff.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MsgField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConnectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(speakerBox)
                        .addGap(32, 32, 32)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConnectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(speakerBox, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(userScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SendBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MsgField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *Connect the client when the client press the connect button 
     * @param evt 
     */
    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBtnActionPerformed
        username = NameField.getText().trim();
        if (!isConnected) {
            client = new ClientThread(username, AddressField.getText().trim());
            client.start();
        } else {
            client.disconnect();
        }
    }//GEN-LAST:event_ConnectBtnActionPerformed

    /**
     * Send the message if the send button pressed.
     * @param evt 
     */
    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        client.SendMessage(MsgField.getText().trim());
        MsgField.setText("");
    }//GEN-LAST:event_SendBtnActionPerformed

    /**
     * Disconnect the client from the chat if the windows is closed. 
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (isConnected) {
            client.disconnect();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * Online users list,the client pressed on name in the list. 
     * @param evt 
     */
    private void usersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usersListValueChanged
        if (usersList.getSelectedValue() != null) {
            switch (usersList.getSelectedValue()) {
                case "Lobby":
                    MsgField.setText("");
                    MsgField.requestFocus();
                    break;
                default:
                    MsgField.setText("<set_msg><" + usersList.getSelectedValue() + ">");
                    MsgField.requestFocus();
                    break;
            }
        }
    }//GEN-LAST:event_usersListValueChanged
    
    /**
     * Clear button - clear the chat window
     * @param evt 
     */
    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        chatWin.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    /**
     * Ok button in the Dialog pressed, close the dialog
     * @param evt 
     */
    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * Send messsage when the user press ENTER key
     * @param evt 
     */
    private void MsgFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MsgFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            client.SendMessage(MsgField.getText().trim());
            MsgField.setText("");
        }
    }//GEN-LAST:event_MsgFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField AddressField;
    public static javax.swing.JButton ClearBtn;
    public static javax.swing.JButton ConnectBtn;
    public static javax.swing.JLabel ErrorMsg;
    public static javax.swing.JTextField MsgField;
    public static javax.swing.JTextField NameField;
    public static javax.swing.JButton OkButton;
    public static javax.swing.JButton SendBtn;
    public static javax.swing.JTextArea chatWin;
    public static javax.swing.JDialog jDialog1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField nameBox;
    public static javax.swing.JCheckBox speakerBox;
    public static javax.swing.JScrollPane userScrollPanel;
    public static javax.swing.JList<String> usersList;
    // End of variables declaration//GEN-END:variables
}
